In [1]:
# Numpy

In [3]:
import numpy as np #2005 by Travis Oliphant

In [4]:
np.__version__

'1.23.5'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [6]:
#Why numpy
#-mathematical function
#Faster

In [7]:
np.__version__

'1.23.5'

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [9]:
# why numpy
# mathematical function 
# Faster 

In [11]:
l=[1,2,3,34,4,4]

In [12]:
# it store heterheterogeneous data

In [13]:
np.array(l)

array([ 1,  2,  3, 34,  4,  4])

In [14]:
type(np.array(l))

numpy.ndarray

In [15]:
# ndnumpy n dimensions array 
# array is way numpy store data and it  store same data 

In [16]:
type(np.array(l))

numpy.ndarray

In [19]:
arr=np.array(l)

In [20]:
arr

array([ 1,  2,  3, 34,  4,  4])

In [21]:
type(np.array(l))

numpy.ndarray

In [24]:
arr.ndim
# 1 dimension array 

1

In [25]:
l=[1,2,3,4,5,6,"ajay"]
arr1=np.array(l)
arr1

array(['1', '2', '3', '4', '5', '6', 'ajay'], dtype='<U21')

In [26]:
arr1=np.array([[1,2,3],[4,6,7]])

In [28]:
arr1

array([[1, 2, 3],
       [4, 6, 7]])

In [31]:
arr1.ndim
# 2 dimension array 

2

In [32]:
l=[1,2,3,45]

In [34]:
np.array(l)

array([ 1,  2,  3, 45])

In [44]:
np.matrix(l)
mat = np.matrix(l) 

In [45]:
np.matrix ([[1,2,3],[4,56,6],[7,8,7]])

matrix([[ 1,  2,  3],
        [ 4, 56,  6],
        [ 7,  8,  7]])

In [48]:
# more way to convert to array 
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [49]:
np.ndim(l)

1

In [50]:
np.asanyarray([[[1,2],[4,5],[7,9]]])

array([[[1, 2],
        [4, 5],
        [7, 9]]])

In [51]:
mat

matrix([[ 1,  2,  3, 45]])

In [52]:
np.asanyarray(mat)

matrix([[ 1,  2,  3, 45]])

In [53]:
np.ndim(mat)

2

In [54]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [55]:
np.array([[[1,2],[4,5],[7,9]]])

array([[[1, 2],
        [4, 5],
        [7, 9]]])

In [17]:
import numpy as np
t=([1,2,3],[4,6,7])
type(t)
np.array(t)

array([[1, 2, 3],
       [4, 6, 7]])

In [61]:
a=2
np.array(a)

array(2)

In [13]:
l=[12,34,56,76]
arr=np.array(l)
arr


array([12, 34, 56, 76])

In [18]:
arr[0]

12

In [19]:
a=arr

In [20]:
a


array([12, 34, 56, 76])

In [21]:
arr[0]=1000

In [22]:
arr

array([1000,   34,   56,   76])

In [23]:
a

array([1000,   34,   56,   76])

In [24]:
# shallow copy upper example 
# deep copy below example

In [25]:
b=a.copy()
b[0]=101

In [26]:
b

array([101,  34,  56,  76])

In [27]:
a

array([1000,   34,   56,   76])

In [28]:
# to create array ->> array ,asarray ,asanyarray ,aeep copy ,shallow copy
# there are multiple way to generating arrays

In [30]:
np.fromfunction(lambda i ,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
l=([[1,2],[4,5]])
arr=np.array(l)
arr

array([[1, 2],
       [4, 5]])

In [34]:
arr

array([[1, 2],
       [4, 5]])

In [35]:
arr.shape

(2, 2)

In [36]:
#(2 -> row and 2 -> colcolumn )

In [38]:
a.shape

(4,)

In [39]:
# (4 -> represenation of element in 1 dimension array element)


In [40]:
np.fromfunction(lambda i ,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
#[012 * 012 create combination ]
# multiplication in row and column


In [42]:
np.fromfunction(lambda i ,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [43]:
range(5)

range(0, 5)

In [44]:
for i in range(5):
    print(i)

0
1
2
3
4


In [45]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [47]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [65]:
import numpy as np
iterable=(i*i for i in range(5))


In [66]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [68]:
np.fromiter(iterable,float)

array([], dtype=float64)

In [53]:
np.fromstring('23 34 34',sep= ' ' )

array([23., 34., 34.])

In [54]:
np.fromstring(' bajrarng ,ajay ,23 34 34',sep= ' ' )

/tmp/ipykernel_1813/3023945545.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring(' bajrarng ,ajay ,23 34 34',sep= ' ' )


array([-1.])

In [58]:
np.fromstring(' bajrarng ,ajay ',sep= ' ' )

/tmp/ipykernel_1813/1534148344.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring(' bajrarng ,ajay ',sep= ' ' )


array([-1.])

In [69]:
arr

array([[1, 2],
       [4, 5]])

In [70]:
a

array([1000,   34,   56,   76])

In [71]:
a.shape

(4,)

In [72]:
arr.shape

(2, 2)

In [73]:
l=[12,34,3]
arr=np.array(l)
arr

array([12, 34,  3])

In [74]:
arr

array([12, 34,  3])

In [75]:
list(range(5))

[0, 1, 2, 3, 4]

In [76]:
range(5)

range(0, 5)

In [77]:
list(range(1.2,2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [84]:
import numpy as np
np.arange(0.1,10.2)


array([ 0.1,  1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1])

In [85]:
np.arange(0.1,10.2,0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1])

In [86]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [87]:
list(np.arange(0.1,10.2,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001]

In [5]:
import numpy as np
"""x = np.linspace(start, stop, num)
  linspace () instead of linespace() 
  it take random value 
"""
x=np.linspace(1,5,20)

In [6]:
x

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [7]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [9]:
np.logspace(1,5,10,base=3)

array([  3.        ,   4.88849467,   7.96579337,  12.98024613,
        21.151288  ,  34.46598619,  56.16226322,  91.51630808,
       149.12566131, 243.        ])

In [10]:
"""
numpy.linspace(start, stop, num): This function returns num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded123.
numpy.logspace(start, stop, num): This function returns num samples, equally spaced on a log scale. In linear space, the sequence starts at base ** start and ends with base ** stop

"""
import numpy as np

# Using linspace
lin = np.linspace(1, 10, 10)
print("linspace:", lin)

# Using logspace
log = np.logspace(0, 1, 10)
print("logspace:", log)


linspace: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
logspace: [ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr=np.zeros((3,2))

In [19]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
arr.shape

(3, 2)

In [21]:
arr.ndim

2

In [22]:
arr3=np.zeros((3,3,4))
arr3.shape


(3, 3, 4)

In [23]:
arr3.ndim

3

In [26]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr=np.ones((3,3,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
arr*4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [31]:
arr+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [32]:
np.array([[[[[[[[[[1,2,3,4]]]]]]]]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (325641959.py, line 1)

In [33]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [34]:
l = [1, 2,3, 4,5, "Prince"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [ ]:
########interview Question###########
# what numpy 
# what array 
# list vs array 
# why array in faster than list
# homogenous 
# memory allocations 
