In [1]:
# numpy advances 

In [5]:
import numpy as np
arr =np.ones((3,4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr +5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [8]:
arr *3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [9]:
arr /3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [18]:
np.empty((3,4),bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
 np.eye(5)  # n* n matrix to calculates inverse of matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
#option

import pandas as pd 
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [31]:
# extra topics 
import random 

In [37]:
random.choice((1,2,3,4,5,6))

1

In [38]:
random.choice((1,2,3,4,5,6))

3

In [40]:
random.choice("ajay")

'a'

In [42]:
random.randrange(1,1000)

569

In [54]:
random.random()   # a random number between no is generate 0 and 1 between number  


0.5885676980141261

In [46]:
lis=[1,2,3,4,5]
random.shuffle(lis)

In [47]:
lis

[3, 4, 2, 1, 5]

In [53]:
random.uniform(7,14)  # a no between 7 and 14

11.51841203585186

In [55]:
np.random.rand(2,3)

array([[0.54112468, 0.17520369, 0.83446182],
       [0.07233987, 0.61832211, 0.53115029]])

In [56]:
np.random.rand(1)

array([0.23313651])

In [59]:
np.random.randn(2,3)

array([[-0.10833505,  0.54870255, -0.2561842 ],
       [-0.36717666,  1.49052208, -0.70608613]])

In [60]:
np.random.random_sample()

0.1931836512492744

In [61]:
np.random.randint(1,5 ,size= (3,2))

array([[3, 4],
       [1, 1],
       [3, 1]])

In [62]:
arr.size

12

In [63]:
arr.shape

(3, 4)

In [64]:
arr.ndim

2

In [65]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [70]:
arr.reshape(2,1)      # array size can not change at any point

ValueError: cannot reshape array of size 12 into shape (2,1)

In [74]:
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
arr.reshape(2,  6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [79]:
arr.reshape(4, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
arr.reshape(3, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
arr.reshape(4 ,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
arr.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [87]:
arr.reshape(-1,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
# size is determine already in before example 

In [91]:
arr.reshape(3,4).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
arr.reshape(12, ).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [114]:
import numpy as np
arr1=np.ones((3,4))
arr1
arr1 *3
arr1

np.random.randn(3,4)
np.random.random_sample()

0.7733082385490951

In [115]:
arr.size

12

In [116]:
arr.reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [117]:
arr.reshape(1,2,2,3)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [118]:
arr.reshape(4,3,1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [120]:
arr.reshape(1,1,1,1,1,1,1,1,1,1,1,2,2,3)

array([[[[[[[[[[[[[[1., 1., 1.],
                   [1., 1., 1.]],

                  [[1., 1., 1.],
                   [1., 1., 1.]]]]]]]]]]]]]])

In [121]:
# dimension 

In [130]:
lis=[1,2,3,4]
arr= np.array(lis)

In [131]:
arr

array([1, 2, 3, 4])

In [132]:
arr.ndim

1

In [134]:
arr2=np.array([[2,3],[4,5]])

In [135]:
arr2

array([[2, 3],
       [4, 5]])

In [136]:
arr2.ndim

2

In [137]:
arr2=np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
arr2.ndim

2

In [149]:
arr3=np.zeros((2,3,4)) # 3 row and 4 column  >> 2d array  + d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [150]:
arr3.ndim

3

In [151]:

arr4=np.zeros((1,1,3,4)) # 3 row and 4 column  >> 2d array  + 1d + 1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [152]:
arr4.ndim

4

In [153]:
arr4.shape

(1, 1, 3, 4)

In [154]:
arr3.shape

(2, 3, 4)

In [155]:
arr3.ndim

3

In [157]:
arr1= np.random.randint(1,10,(5,6))

In [158]:
arr1

array([[9, 5, 1, 3, 1, 5],
       [2, 9, 3, 3, 1, 9],
       [8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [159]:
arr1.ndim

2

In [160]:
arr1.shape

(5, 6)

In [162]:
arr1 > 5

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False,  True],
       [ True,  True, False,  True, False,  True],
       [False,  True,  True, False, False, False],
       [ True,  True, False,  True,  True, False]])

In [164]:
arr1 [arr1 > 5] # give me the value of avery  where condition is true

array([9, 9, 9, 8, 7, 8, 6, 7, 7, 9, 9, 9, 8])

In [166]:
arr1[arr1 < 5 ]

array([1, 3, 1, 2, 3, 3, 1, 3, 2, 4, 1, 2, 2, 1, 1])

In [167]:
arr1

array([[9, 5, 1, 3, 1, 5],
       [2, 9, 3, 3, 1, 9],
       [8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [168]:
arr

array([1, 2, 3, 4])

In [169]:
arr[0]

1

In [170]:
arr[3]

4

In [171]:
arr1[1]

array([2, 9, 3, 3, 1, 9])

In [175]:
arr1[0]

array([9, 5, 1, 3, 1, 5])

In [176]:
arr1

array([[9, 5, 1, 3, 1, 5],
       [2, 9, 3, 3, 1, 9],
       [8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [180]:
arr1[0 ,[1,3]] # slicing in element in the matrix 

array([5, 3])

In [182]:
arr1[2:4,[2,3]]

array([[3, 8],
       [7, 1]])

In [195]:
arr1[2:4] # accessing row in matrix 

array([[8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2]])

In [196]:
arr1[2:4, [4,3]]

array([[2, 8],
       [2, 1]])

In [197]:
arr1

array([[9, 5, 1, 3, 1, 5],
       [2, 9, 3, 3, 1, 9],
       [8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [198]:
arr1[0]

array([9, 5, 1, 3, 1, 5])

In [199]:
arr1[2:5]

array([[8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [201]:
arr1[0:5 ,[0,1]]  # acessing column # slicing 

array([[9, 5],
       [2, 9],
       [8, 7],
       [4, 7],
       [9, 9]])

In [203]:
arr1[1:5 ,[0,3]]

array([[2, 3],
       [8, 8],
       [4, 1],
       [9, 9]])

In [205]:
arr1[[2,4]]

array([[8, 7, 3, 8, 2, 6],
       [9, 9, 1, 9, 8, 1]])

In [206]:
arr1

array([[9, 5, 1, 3, 1, 5],
       [2, 9, 3, 3, 1, 9],
       [8, 7, 3, 8, 2, 6],
       [4, 7, 7, 1, 2, 2],
       [9, 9, 1, 9, 8, 1]])

In [207]:
arr1[2]

array([8, 7, 3, 8, 2, 6])

In [209]:
arr1[[2,4]]

array([[8, 7, 3, 8, 2, 6],
       [9, 9, 1, 9, 8, 1]])

In [210]:
arr1[[2,4],[3,4]]

array([8, 8])

In [213]:
arr1[2:4,[1,4]]

array([[7, 2],
       [7, 2]])

In [216]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [217]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [218]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [222]:
arr1 +arr2  # index of multiplication not matrix multiplication

array([[2, 3, 4],
       [3, 2, 3],
       [4, 2, 3]])

In [220]:
arr1*arr2

array([[1, 2, 4],
       [2, 1, 2],
       [4, 1, 2]])

In [221]:
arr1 -arr2

array([[ 0, -1,  0],
       [-1,  0,  1],
       [ 0,  0, -1]])

In [223]:
# matrix multiplication 


In [224]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [225]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [226]:
arr1 @ arr2

array([[7, 5, 7],
       [7, 5, 7],
       [6, 6, 7]])

In [227]:
arr1 /arr2

array([[1. , 0.5, 1. ],
       [0.5, 1. , 2. ],
       [1. , 1. , 0.5]])

In [228]:

5 / 0

ZeroDivisionError: division by zero

In [229]:

arr1 /0

/tmp/ipykernel_151/655778564.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 /0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [230]:
# broad casting 
# adding element in each element 

In [233]:
arr =np.zeros((3,4))

In [234]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [235]:
arr +5 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [236]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [237]:
a=np.array([1,2,3,4])

In [238]:
a

array([1, 2, 3, 4])

In [239]:
arr +a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [249]:
a=np.array([[1,2,3]])

In [250]:
a

array([[1, 2, 3]])

In [251]:
 arr +a     # in this operation not working because row in doesn't work 

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [254]:
a.T     # T -> transport is using row element in column 

array([[1],
       [2],
       [3]])

In [255]:
arr +a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [256]:
a=np.array([1,2,3])
a.T

array([1, 2, 3])

In [257]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [258]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [259]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [260]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [261]:
np.min(arr1)

1

In [262]:
np.max(arr1)

2

In [263]:
a

array([1, 2, 3])

In [264]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [265]:
np.min(a)

1

In [266]:
np.max(a)

3

In [269]:
arr1.flatten()# reduce higher dimension to 1 d

array([1, 1, 2, 1, 1, 2, 2, 1, 1])

In [270]:
# expand_ dimen >> expands the array by inserting a new axis 

In [275]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [276]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
np.sum(arr)

45

In [282]:
np.sum(arr ,axis =0) # through with seen column wise but it called rowswise

array([12, 15, 18])

In [283]:
np.sum(arr,axis =1) # through it seen row wise but it called columnwise

array([ 6, 15, 24])

In [284]:
# expand_dim >> expand the dimension of array 

In [285]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [286]:
arr.ndim

1

In [288]:
arr1=np.expand_dims(arr,axis =0)

In [292]:
arr1
arr1.ndim

2

In [293]:
arr1.shape

(1, 4)

In [296]:
arr2=np.expand_dims(arr1,axis =1)

In [297]:
arr2

array([[[1, 2, 3, 4]]])

In [299]:
arr2.ndim

3

In [301]:
arr2.shape

(1, 1, 4)

In [302]:
arr2

array([[[1, 2, 3, 4]]])

In [303]:
arr

array([1, 2, 3, 4])

In [304]:
arr1=np.expand_dims(arr,axis =1)

In [305]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [306]:
arr1.ndim

2

In [307]:
arr1.shape

(4, 1)

In [308]:
arr=np.zeros((3,4))

In [309]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [310]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [311]:
arr1=np.expand_dims(arr,axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])