## 1. What is a Python library? Why  we do use Python libraries?

A Python library is a collection of related modules. These libraries contain bundles of code that can be reused across different programs. Let me explain why we use Python libraries:

Code Reusability: Libraries allow us to avoid writing the same code repeatedly for different programs. Instead, we can leverage pre-existing functionality from libraries, making our programming tasks simpler and more convenient.

Specific Operations: Each library focuses on specific tasks or domains. For example:

TensorFlow: Developed by Google, TensorFlow is an open-source library used for high-level computations, machine learning, and deep learning algorithms.

Matplotlib: This library is essential for plotting numerical data, creating high-quality figures like pie charts, histograms, and scatterplots.

Pandas: A crucial library for data scientists, Pandas provides flexible data structures and analysis tools.

Python Standard Library: Python comes with a built-in standard library that contains more than 200 core modules. These modules provide access to basic system functionality, I/O operations, and other essential features. Without the standard library, Python programmers wouldn’t have access to these functionalities.

## 2. What is the difference between Numpy array and List?

Homogeneity:

    NumPy Arrays: These store elements of the same data type in a homogeneous manner. This compact arrangement makes them memory-efficient.

    Python Lists: Lists can hold different data types (heterogeneous). However, this flexibility can decrease memory efficiency and slow down numerical operations.

Data Type:

    NumPy Arrays: Have a fixed data type, which reduces memory overhead. No need to store type information for each element.
    
    Python Lists: Store additional information about each element, including its type and reference count. This overhead can be significant when dealing with a large number of elements.
    
Memory Layout:
    
    NumPy Arrays: Elements are stored contiguously in memory. For example, all rows of a 2D array must have the same number of columns.

    Python Lists: Elements need not be contiguous in memory, potentially causing memory fragmentation.

Performance:

    NumPy Arrays: Optimized for numerical computations and perform faster vectorized operations.

    Python Lists: Not optimized for numerical tasks due to Python’s interpretation overhead. They serve as general-purpose data structures.

In [1]:
## 3. Fin^ the shape, size an^ ^imension of the following array?
"""
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]] """

import numpy as np
data=np.array([[1, 2, 3, 4],
      [5, 6, 7, 8],
     [9, 10, 11, 12]])

In [2]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
data.shape

(3, 4)

In [4]:
data.ndim


2

In [5]:
## 4. Write python co^e to access the first row of the following array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

data1=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [6]:
data1[0:1]

array([[1, 2, 3, 4]])

In [7]:
data1[0::3]

array([[1, 2, 3, 4]])

In [8]:
## 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

data=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [9]:
data[::, 3]

array([ 4,  8, 12])

In [10]:
data[2,3]

12

In [11]:
## 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
'''[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

data_odd=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [12]:
data_odd=data[:,0::2]
data_odd

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [13]:
even_number=data[:,1::2]
even_number

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [14]:
## 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

data3=np.random.rand(3,3)
data3 

array([[0.16234786, 0.76784665, 0.21385525],
       [0.98812917, 0.83616062, 0.88760455],
       [0.06397979, 0.18543628, 0.35406452]])

In [15]:
## 9. Write co^e to increase the ^imension of the following array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

data.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
## 10. How to transpose the following array in NumPy?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

data.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
data.transpose((1,0))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
## 11. Consi^er the following matrix:
'''
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matricK
4. Subtract matrix B from A
5. Divide Matrix B by A'''

A2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [19]:
A2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
B2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
#1. Index wise multiplication
A2*B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [22]:
#2. Matrix multiplication
A2.transpose()
# solve

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [23]:
# 3. Add both the matricK
A2+B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [24]:
# 4. Subtract matrix B from A
B2 - A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
# 5. Divide Matrix B by A
A2 / B2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

Certainly! In NumPy, you can use the **`ndarray.byteswap()`** method to swap the byte order of an array. This function allows you to toggle between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place. Here's how it works:

1. **`ndarray.byteswap(inplace=False)`**:
    - Swaps the bytes of the array elements.
    - If `inplace` is set to `True`, the operation modifies the original array in-place.
    - If `inplace` is set to `False` (default), a new byteswapped array is returned.
    - Note that arrays of byte-strings are not swapped, and the real and imaginary parts of a complex number are swapped individually.

Example usage:

```python
import numpy as np

# Create an example array (you can replace this with your own data)
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
swapped_array = original_array.byteswap()

print("Original array:")
print(original_array)
print("Swapped array:")
print(swapped_array)
```

The `swapped_array` will have its byte order reversed compared to the `original_array`. You can use this function when dealing with data written in a machine with a different byte order than the one where it is being read¹²³.



## 13.  What is the significance of the np.linalg.inv function? in python

The **`np.linalg.inv`** function in Python, provided by the **NumPy** library, serves a crucial purpose in linear algebra and numerical computations. Let's delve into its significance:

1. **Matrix Inversion**:
   - The primary role of `np.linalg.inv` is to compute the **multiplicative inverse** of a square matrix.
   - Given a square matrix **`a`**, it returns the matrix **`ainv`** such that:
     - **`dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])`**
     - Here, **`eye(a.shape[0])`** represents the identity matrix of the same size as matrix **`a`**.
   - In simpler terms, if you multiply a matrix by its inverse, you get the identity matrix.
   - This operation is essential for solving systems of linear equations, finding determinants, and other mathematical tasks.

2. **Use Cases**:
   - **Solving Linear Systems**:
     - When solving systems of linear equations, you can express them in matrix form **`Ax = b`**.
     - To find the solution vector **`x`**, you compute **`x = np.dot(np.linalg.inv(A), b)`**.
   - **Eigenvalue Problems**:
     - Eigenvalues and eigenvectors play a crucial role in various scientific and engineering applications.
     - Matrix inversion is often involved in eigenvalue computations.
   - **Least Squares Regression**:
     - In regression analysis, matrix inversion helps find the coefficients that minimize the sum of squared residuals.
   - **Numerical Stability**:
     - Matrix inversion is numerically sensitive, especially for ill-conditioned matrices.
     - The **pseudoinverse** (computed using **`np.linalg.pinv`**) is more robust in such cases.

3. **Example**:
   ```python
   import numpy as np

   # Create a sample matrix 'a'
   a = np.array([[1., 2.], [3., 4.]])

   # Compute the inverse
   ainv = np.linalg.inv(a)

   # Verify properties
   assert np.allclose(np.dot(a, ainv), np.eye(2))
   assert np.allclose(np.dot(ainv, a), np.eye(2))
   ```

4. **Notes**:
   - Broadcasting rules apply when using `np.linalg.inv`.
   - If **`a`** is a matrix object, the return value is also a matrix.
   - Ensure that **`a`** is square; otherwise, a **`LinAlgError`** will be raised.

In summary, `np.linalg.inv` empowers Python programmers with matrix inversion capabilities, making it a fundamental tool for scientific computing and data analysis¹²³⁴⁵.



## 14. What ^oes the np.reshape function ^o, an^ how is it use^?

The **`np.reshape`** function in Python, provided by the **NumPy** library, is a powerful tool for changing the shape of an array without altering its data. Let's explore its significance and usage:

1. **Purpose of `np.reshape`**:
   - The primary purpose of `np.reshape` is to **rearrange the dimensions** of an existing array.
   - It allows you to create a new view of the data with a different shape, without copying the underlying elements.
   - You can reshape arrays to match specific requirements for mathematical operations, visualization, or other tasks.

2. **Syntax**:
   - The syntax for `np.reshape` is as follows:
     ```python
     np.reshape(a, newshape, order='C')
     ```
     - `a`: The input array to be reshaped.
     - `newshape`: An integer or a tuple of integers representing the desired new shape.
     - `order`: Optional parameter specifying the index order for reading and placing elements (options: `'C'`, `'F'`, `'A'`).

3. **Behavior and Examples**:
   - Reshaping is like first **"raveling"** the array (using the given index order), and then inserting the elements from the raveled array into the new shape.
   - Let's consider an example:
     ```python
    
4. **Use Cases**:
   - **Data Preparation**:
     - When working with data for machine learning models, reshaping allows you to organize features or samples.
   - **Image Processing**:
     - Images are often represented as multi-dimensional arrays. Reshaping helps convert image data into suitable formats.
   - **Matrix Operations**:
     - Reshaping is crucial for matrix multiplication, transposition, and other linear algebra operations.

5. **Notes**:
   - The order keyword affects both fetching values from the original array and placing them into the reshaped array.
   - Be aware that not all shapes are compatible without copying data.
   - The returned array may be a new view or a copy, depending on memory layout.

In summary, `np.reshape` is a versatile function that allows you to manipulate array shapes efficiently, making it essential for scientific computing and data analysis¹²³⁴⁵..


In [33]:
## Example

import numpy as np


a = np.arange(6).reshape((3, 2))
    
     # array([[0, 1],
     #        [2, 3],
     #        [4, 5]])

     # Reshape 'a' to a 2x3 array (C-like index ordering)
result_c_order = np.reshape(a, (2, 3))
    
     # array([[0, 1, 2],
     #        [3, 4, 5]])

     # Equivalent to raveling 'a' and then reshaping (C-like order)
equivalent_result = np.reshape(np.ravel(a), (2, 3))

     
     # Reshape 'a' with Fortran-like index ordering
result_f_order = np.reshape(a, (2, 3), order='F')
   
     # array([[0, 4, 3],
     #        [2, 1, 5]])
    


## 15. What is broadcasting in Numpy?

**Broadcasting** in **NumPy** is a powerful concept that allows arrays with different shapes to interact seamlessly during arithmetic operations. Let's explore this further:

1. **What Is Broadcasting?**
   - Broadcasting enables NumPy to handle arrays of varying shapes in a way that makes them compatible for element-wise operations.
   - When two arrays are broadcast, the smaller one is virtually "stretched" or replicated to match the shape of the larger array.
   - This process avoids unnecessary data copies and promotes efficient computation.

2. **Basic Broadcasting Examples**:
   - **Multiplying Arrays**:
     - Consider two arrays:
       ```python
       a = np.array([1.0, 2.0, 3.0])
       b = np.array([2.0, 2.0, 2.0])
       ```
     - Without broadcasting, both arrays must have the same shape for element-wise multiplication.
     - However, broadcasting allows us to perform the operation:
       ```python
       result = a * b  # array([2., 4., 6.])
     - Here, the scalar **`b`** is effectively stretched to match the shape of **`a`** during multiplication.

3. **General Broadcasting Rules**:
   - NumPy compares array shapes element-wise, starting from the trailing dimensions.
   - Dimensions are compatible if they are equal or one of them is 1.
   - If shapes are incompatible, a **`ValueError`** is raised.
   - Input arrays can have different numbers of dimensions.
   - The resulting array has the same number of dimensions as the input array with the greatest number of dimensions.
   - Missing dimensions are assumed to have size one.

4. **Example: RGB Image Scaling**:
   - Suppose you have a 256x256x3 array representing RGB values in an image.
   - To scale each color channel by different values, you can multiply the image by a one-dimensional array with 3 values.

5. **Benefits of Broadcasting**:
   - Efficient vectorization of operations.
   - Avoids unnecessary memory overhead.
   - Enables concise and readable code.

Remember, broadcasting simplifies array operations, making NumPy a versatile tool for scientific computing and data analysis¹²³⁴.



In [37]:
## **Combining Array and Scalar**:
 #    - Broadcasting also works when combining an array with a scalar:
import numpy as np      
a = np.array([1.0, 2.0, 3.0])
b = 2.0
result = a * b  # array([2., 4., 6.])