In [1]:
import numpy as np
data=np.array([[1],[2],[3]])

In [2]:
data

array([[1],
       [2],
       [3]])

In [5]:
a=np.squeeze(data)

In [6]:
data.ndim

2

In [7]:
a

array([1, 2, 3])

In [8]:
a.ndim

1

In [9]:
#repeat

In [10]:
data

array([[1],
       [2],
       [3]])

In [13]:
np.repeat(data ,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
a=np.array([[1,2],[3,4]])

In [17]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
a.ndim

2

In [20]:
a.shape

(2, 2)

In [24]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [25]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [26]:
np.repeat(a,1,axis=1)

array([[1, 2],
       [3, 4]])

In [31]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [32]:
np.diag(np.array([1,2,3,3]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [33]:
a=np.array([[[1,2],[3,4],[5,6]]])

In [34]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [35]:
np.roll(a,1,axis=0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [38]:
np.roll(a,1,axis=1)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [39]:
np.roll(a,2,axis=1)

array([[[3, 4],
        [5, 6],
        [1, 2]]])

In [40]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
# binary operation on array 

In [42]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [43]:
arr1

array([[8, 8, 5, 5],
       [8, 3, 1, 3],
       [4, 7, 5, 4]])

In [44]:
arr2

array([[5, 8, 6, 4],
       [3, 6, 2, 2],
       [6, 7, 8, 2]])

In [45]:
arr1+arr2

array([[13, 16, 11,  9],
       [11,  9,  3,  5],
       [10, 14, 13,  6]])

In [46]:
arr1 * arr2

array([[40, 64, 30, 20],
       [24, 18,  2,  6],
       [24, 49, 40,  8]])

In [47]:
arr1 - arr2

array([[ 3,  0, -1,  1],
       [ 5, -3, -1,  1],
       [-2,  0, -3,  2]])

In [48]:
arr1 ** arr2

array([[   32768, 16777216,    15625,      625],
       [     512,      729,        1,        9],
       [    4096,   823543,   390625,       16]])

In [49]:
arr1 >arr2

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [50]:
arr1 /arr2

array([[1.6       , 1.        , 0.83333333, 1.25      ],
       [2.66666667, 0.5       , 0.5       , 1.5       ],
       [0.66666667, 1.        , 0.625     , 2.        ]])

In [51]:
~arr1

array([[-9, -9, -6, -6],
       [-9, -4, -2, -4],
       [-5, -8, -6, -5]])

In [52]:
~arr2

array([[-6, -9, -7, -5],
       [-4, -7, -3, -3],
       [-7, -8, -9, -3]])

In [53]:
arr1

array([[8, 8, 5, 5],
       [8, 3, 1, 3],
       [4, 7, 5, 4]])

In [54]:
arr2

array([[5, 8, 6, 4],
       [3, 6, 2, 2],
       [6, 7, 8, 2]])

In [57]:
# numpy string function

In [58]:
arr=np.array(["pw","skills"])

In [59]:
arr

array(['pw', 'skills'], dtype='<U6')

In [60]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [61]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [62]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [63]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [64]:
## mathematical function 

arr1

array([[8, 8, 5, 5],
       [8, 3, 1, 3],
       [4, 7, 5, 4]])

In [65]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825, -0.95892427, -0.95892427],
       [ 0.98935825,  0.14112001,  0.84147098,  0.14112001],
       [-0.7568025 ,  0.6569866 , -0.95892427, -0.7568025 ]])

In [66]:
np.tan(arr1)

array([[-6.79971146, -6.79971146, -3.38051501, -3.38051501],
       [-6.79971146, -0.14254654,  1.55740772, -0.14254654],
       [ 1.15782128,  0.87144798, -3.38051501,  1.15782128]])

In [67]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.69897   , 0.69897   ],
       [0.90308999, 0.47712125, 0.        , 0.47712125],
       [0.60205999, 0.84509804, 0.69897   , 0.60205999]])

In [68]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 1.48413159e+02, 1.48413159e+02],
       [2.98095799e+03, 2.00855369e+01, 2.71828183e+00, 2.00855369e+01],
       [5.45981500e+01, 1.09663316e+03, 1.48413159e+02, 5.45981500e+01]])

In [69]:
np.std(arr1)

2.177855724228663

In [70]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.28366219,  0.28366219],
       [-0.14550003, -0.9899925 ,  0.54030231, -0.9899925 ],
       [-0.65364362,  0.75390225,  0.28366219, -0.65364362]])

In [73]:
np.power(arr1 ,2)

array([[64, 64, 25, 25],
       [64,  9,  1,  9],
       [16, 49, 25, 16]])

In [74]:
np.max(arr1)

8

In [75]:
np.min(arr1)

1

In [76]:
arr1 - arr2

array([[ 3,  0, -1,  1],
       [ 5, -3, -1,  1],
       [-2,  0, -3,  2]])

In [78]:
arr1 +arr2

array([[13, 16, 11,  9],
       [11,  9,  3,  5],
       [10, 14, 13,  6]])

In [79]:
np.multiply(arr1 ,arr2)

array([[40, 64, 30, 20],
       [24, 18,  2,  6],
       [24, 49, 40,  8]])

In [80]:
np.mod(arr1,arr2)

array([[3, 0, 5, 1],
       [2, 3, 1, 1],
       [4, 0, 5, 0]])

In [81]:
arr1 * arr2

array([[40, 64, 30, 20],
       [24, 18,  2,  6],
       [24, 49, 40,  8]])

In [82]:
np.power(arr1 ,arr2)

array([[   32768, 16777216,    15625,      625],
       [     512,      729,        1,        9],
       [    4096,   823543,   390625,       16]])

In [83]:
arr1

array([[8, 8, 5, 5],
       [8, 3, 1, 3],
       [4, 7, 5, 4]])

In [84]:
arr2

array([[5, 8, 6, 4],
       [3, 6, 2, 2],
       [6, 7, 8, 2]])

In [85]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 2.23606798, 2.23606798],
       [2.82842712, 1.73205081, 1.        , 1.73205081],
       [2.        , 2.64575131, 2.23606798, 2.        ]])

In [87]:
np.power(arr2 ,3)

array([[125, 512, 216,  64],
       [ 27, 216,   8,   8],
       [216, 343, 512,   8]])

In [88]:
np.min(arr2)

2

In [89]:
np.min(arr1)

1

In [90]:
## sort and search

In [91]:
arr=np.array([53,63,33])

In [92]:
arr

array([53, 63, 33])

In [93]:
np.sort(arr)

array([33, 53, 63])

In [97]:
np.searchsorted(arr , 2)

0

In [98]:
arr=np.array([0,1,2,3,4,5,])

In [99]:
arr

array([0, 1, 2, 3, 4, 5])

In [100]:
np.count_nonzero(arr1)

12

In [101]:
arr1 > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [102]:
arr > 0

array([False,  True,  True,  True,  True,  True])

In [104]:
np.where(arr > 0)

(array([1, 2, 3, 4, 5]),)

In [112]:
np.extract(arr > 0 ,arr) # 2d only 

array([1, 2, 3, 4, 5])

In [113]:
arr1

array([[8, 8, 5, 5],
       [8, 3, 1, 3],
       [4, 7, 5, 4]])

In [114]:
arr

array([0, 1, 2, 3, 4, 5])

In [115]:
arr.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808, 288230376151711744, 360287970189639680])

In [116]:
arr1.byteswap()

array([[576460752303423488, 576460752303423488, 360287970189639680,
        360287970189639680],
       [576460752303423488, 216172782113783808,  72057594037927936,
        216172782113783808],
       [288230376151711744, 504403158265495552, 360287970189639680,
        288230376151711744]])

In [117]:
# matrix >> 2d array


In [118]:
import numpy.matlib as nm

In [120]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [121]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [122]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [127]:
# numpy is linear algebra
import numpy as np

In [129]:
# arr3=np.random.randint(1,10(3,4))
# arr4=np.random.randint(1,10(3,4))

In [130]:
arr1=np.array([[2,3],[3,4]])
arr2=np.array([[2,3],[3,4]])

In [131]:
arr1 @ arr2

array([[13, 18],
       [18, 25]])

In [132]:
a=np.array([[-4,4,5],[8,-6,5],[3,6,-5]])

In [133]:
a

array([[-4,  4,  5],
       [ 8, -6,  5],
       [ 3,  6, -5]])

In [134]:
b=np.array([15,3,-3])

In [135]:
b

array([15,  3, -3])

In [137]:
np.linalg.solve(a,b)  # LINEAR ALGEBRA EQUACTION

array([0.  , 1.2 , 2.04])

In [142]:
arr1 # determinant of matrix  AA-1 

array([[2, 3],
       [3, 4]])

In [143]:
np.linalg.inv(arr1)

array([[-4.,  3.],
       [ 3., -2.]])